### ISSUE TITLE
Search failes with tumblr blogs

### ISSUE THREAD

**Issue by samim23** [DBeath/feedsearch-crawler#1]
Not sure why, but feedsearch-crawler search seem to fail when trying to discover/process tumblr blog feeds. For example try https://breebird33.tumblr.com/ (or direct https://breebird33.tumblr.com/rss) or https://neurocorp.tumblr.com/ (or direct https://neurocorp.tumblr.com/rss). Both can be flawlessly discovered/consumed with feedly.com.

**Comment by DBeath** [comment]
I'm not sure why you're not able to find those feeds. I don't have any problems finding those feeds when I run the crawler with the default settings. Are you able to attach the debug log output?

**Comment by samim23** [comment]
I've tried to attach the logger as described in your how-to but the log seems to be empty (see screenshot here https://i.imgur.com/aofVmAv.png). Any idea what i might be doing wrong? thanks!

**Comment by samim23** [comment]
The logs seem to be empty, see this screenshot: https://i.imgur.com/aofVmAv.png 
Is it possible i'm doing something wrong here? Any other tips?

**Comment by DBeath** [comment]
Ok, I see the problem. Your crawl is running into Tumblr's privacy agreement page, and can't find anything past that. Unfortunately I don't have any functionality for getting past privacy pages and various other gates, and that's a problem that I don't have the time to make a priority. I'm open to suggestions, info links, or pull requests though.

I followed your profile links, and it looks like you're currently in Germany. I get the exact same response as you if I set my VPN to run from there. I don't get the privacy page here in Switzerland or from a US VPN endpoint, so the only solution I can suggest for now is to use a VPN for Tumblr crawls.

If you're not interested in running the crawls yourself, I've got a free API running at https://feedsearch.dev which is crawling from a US Lambda instance.

**Comment by samim23** [comment]
Privacy gates, very interesting (and annyoing) - thanks for the info. It's peculiar that I'm able to open those feeds via a web-browser (using no VPN or such) with out any problem. I was excepting specifying a custom search user_agent might make a difference, but still does not work.

`feeds = search(url='breebird33.tumblr.com',user_agent='Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0')`

**Comment by DBeath** [comment]
I suspect that you already have a Tumblr cookie in your browser, I get the privacy page using a private window and German VPN endpoint.

It's unfortunate and annoying that there are so many barriers to crawling, even if they are understandable. I've experimented a bit with different user agents and other headers, and the results vary depending on the website. In this case using the Googlebot user agent appears to work.

```
feeds = search(url="breebird33.tumblr.com", user_agent="Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)")
```

**Comment by samim23** [comment]
Excellent hack there, works like a charm (even from DE). Thank you very much! Your "feedsearch-crawler" lib combined with the "feedparser" lib makes for a robust python feed discovery/consumption stack, which is great! Feeds are such a powerful but under rated feature of the web, its mind boggling.

**Comment by DBeath** [comment]
Thanks, really I'm glad you find it useful. If you've got any other problems or suggestions I'm happy to help, and I totally agree with your opinion on feeds, they're criminally underrated these days.
